-- Tworzenie usera dla konkretnej bazy danych

CREATE DATABASE VLO2025
COLLATE SQL_Latin1_General_CP1_CI_AS
GO

USE VLO2025
GO;

CREATE SCHEMA Users AUTHORIZATION dbo
GO
CREATE SCHEMA HR AUTHORIZATION dbo 
GO

CREATE LOGIN VLOUSER01
WITH PASSWORD = 'SecurePass123!',
CHECK_POLICY = ON
GO

CREATE USER VLOUSER01 FOR LOGIN VLOUSER01

ALTER ROLE db_owner ADD MEMBER VLOUSER01

EXECUTE AS USER = 'VLOUSER02'
SELECT * FROM Audit.CustomerChanges
REVERT

DROP USER VLOUSER02